[Feature] Add AWS RUM Integration
Experience-Monks/nextjs-boilerplate pull request #298
Opened 2023-09-15 18:46 UTC by alex-togo

Jira Ticket ID: <JIRA Ticket ID> 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [ ] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Did you test your solution?**

- [ ] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description

## Solution Description

## Side Effects, Risks, Impact

- [ ] N/A

**Aditional comments:**

2023-09-15 18:54 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-1472322.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-09-25 15:28 UTC, edgardz commented on package.json
> +    "aws-rum-web": "^1.14.0",
Hey @alex-togo can you check this package size? The NPM page says 1.27 MB (!!!) Is this true?

2023-10-06 16:41 UTC, fzhang13 commented on package.json
> +    "aws-rum-web": "^1.14.0",
minified version seems to be 136kb according to bundlephobia

2023-10-08 16:07 UTC, alex-togo commented on package.json
> +    "aws-rum-web": "^1.14.0",
@edgardz yeah the unpacked size is currently 1.31mb according to the NPM site, and 136.2kb minifed as Felix mentioned. Is the unpacked size going to be a problem with this package?

2023-10-08 16:15 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-ae6c134.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-10-08 17:33 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-ca1ad80.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-10-11 15:18 UTC, edgardz requested changes

2023-10-11 15:24 UTC, edgardz commented on .env.production
> +NEXT_PUBLIC_APP_REGION=$RUM_APP_REGION
I'm considering if we should set a single env var with JSON encoded values, instead of introducing 7 new env vars. What do you think?

2023-10-20 21:05 UTC, alex-togo commented on src/services/aws-rum.ts
> +      const APPLICATION_VERSION = process.env.NEXT_PUBLIC_APP_VERSION || ''
Yes, this is the version number of RUM.

2023-11-01 20:06 UTC, alex-togo commented on .env.production
> +NEXT_PUBLIC_APP_REGION=$RUM_APP_REGION
Great suggestion, I didn't even know this was possible, really cool!

2023-11-07 15:09 UTC, edgardz requested changes

2023-11-07 15:09 UTC, edgardz commented on src/pages/_app.tsx
> +  }, [cookieConsent])
Don't add this dependency here. The code in this effect is supposed to run only once. Create another effect instead.

2023-11-08 22:37 UTC, edgardz approved these changes

2023-11-08 22:37 UTC, merged